/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.ConnectionProvider;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class billing1 extends javax.swing.JFrame {

    /**
     * Creates new form billing1
     */
    public int traTien = 0;
    public int them = 0;
    public int bang1 = 0;
    public int bang2 = 0;
    public int bang3 = 1;
    public int update = 0;
    Timer updateTimer;
    int DELAY = 100;
    public int xoa = 0;
    public billing1() {
        initComponents();
        updateTimer = new Timer(DELAY, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                Date currentTime = new Date();
                String formatTimeStr = "HH:mm:ss";
                DateFormat formatTime = new SimpleDateFormat(formatTimeStr);
                String formattedTimeStr = formatTime.format(currentTime);
                jLabel14.setText(formattedTimeStr);;
            }
        });
        updateTimer.start();
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jLabel25.setVisible(false);
        jTextField8.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\all page background image.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Billing");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 12, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 12, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, 1342, 6));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "NumberPhone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 170, 401, 153));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "pId", "pName", "Species", "Price"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 170, 400, 153));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Bill", "pId", "pName", "Species", "Price", "Name", "NumberPhone", "Date"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 508, 986, 239));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Customer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 126, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Pet");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 126, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Bill");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 452, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ID_Bill");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 331, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 329, 73, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 361, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("NumberPhone");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 387, -1, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 392, 200, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 359, 201, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("pId");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 343, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("pName");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 385, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 341, 97, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 197, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 197, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 114, 42, 633));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Time");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 64, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 22, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("HH:mm:ss");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1154, 64, 178, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("dd/mm/yyyy");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1154, 22, 178, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 204, 280, 10));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Species");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(843, 349, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 347, 108, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-event-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Add");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 250, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow-back-1-icon (1).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 12, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset (1).png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 12, 110, 80));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Manipulation Tool");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 146, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-delete-icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, 98, 73));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("Delete");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Species");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 138, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Dog", "Cat" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 133, 88, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Status");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 474, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unconfirmed", "Confirmed" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 469, 194, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print-icon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 580, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("Revenue");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 690, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payment-icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, 98, 72));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Paid");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 420, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/create-new-page-icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 490, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setText("Create");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 510, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Paid");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 445, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 443, 200, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/list-icon.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 670, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("Print");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 600, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            Connection con = ConnectionProvider.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select pId,pName,Species,Price from Pet where Status = 1");
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try {
            Connection con = ConnectionProvider.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select Name,NumberPhone from Buyer");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try {
            Connection con = ConnectionProvider.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select ID_Bill,pId,pName,Species,Price,Name,NumberPhone,Date from Bill where Status = 1");
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        DateTimeFormatter dtf1 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        jLabel15.setText(dtf1.format(now));
        jButton5.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new billing1().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String loai = jComboBox1.getSelectedItem().toString();
        try {
            Connection con = ConnectionProvider.getConnection();
            Statement st = con.createStatement();
            if(loai.equals("All")){
                ResultSet rs = st.executeQuery("select pId,pName,Species,Price from Pet where Status = 1");
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            }else{
                ResultSet rs = st.executeQuery("select pId,pName,Species,Price from Pet where Species='"+loai+"' and Status = 1");
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            }
            jTable2.setVisible(false);
            jTable2.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(xoa == 0 && bang1 == 1){
            int row = jTable1.getSelectedRow();
            if(row >= 0){
                jTextField3.setText(jTable1.getValueAt(row, 0).toString());
                jTextField3.setForeground(new Color(0,0,0));
                jTextField2.setText(jTable1.getValueAt(row, 1).toString());
                jTextField2.setForeground(new Color(0,0,0));
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        if(xoa == 0 && bang2 == 1){
            int row = jTable2.getSelectedRow();
                if(row >= 0){
                    jTextField4.setText(jTable2.getValueAt(row, 0).toString());
                    jTextField4.setForeground(new Color(255,0,0));
                    jTextField5.setText(jTable2.getValueAt(row, 1).toString());
                    jTextField5.setForeground(new Color(0,0,0));
                    jTextField7.setText(jTable2.getValueAt(row, 2).toString());
                    jTextField7.setForeground(new Color(0,0,0));
                    jTextField6.setText(jTable2.getValueAt(row, 3).toString());
                    jTextField6.setForeground(new Color(0,0,0));
                }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        String status = jComboBox2.getSelectedItem().toString();
        if(status.equals("Confirmed")){
            jButton5.setEnabled(true);
        }else{
            jButton5.setEnabled(false);
        }
        try {
            Connection con = ConnectionProvider.getConnection();
            Statement st = con.createStatement();
            if (status.equals("Unconfirmed")){
                ResultSet rs = st.executeQuery("select ID_Bill,pId,pName,Species,Price,Name,NumberPhone,Date from Bill where Status = 1");
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                jButton3.setEnabled(true);
            }else if (status.equals("Confirmed")){
                ResultSet rs = st.executeQuery("select ID_Bill,pId,pName,Species,Price,Name,NumberPhone,Date from Bill where Status = 0");
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                jButton3.setEnabled(false);
                jButton2.setEnabled(false);
            }
            jTable3.setVisible(false);
            jTable3.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(them == 0){
            int thongbao = JOptionPane.showConfirmDialog(null, "Bạn muốn tạo đơn hàng?","Select",JOptionPane.YES_NO_OPTION);
            if(thongbao ==0 ){
                bang1 = bang2 = 1;
                bang3 = 0;
                try {
                        Connection con = ConnectionProvider.getConnection();
                        Statement st = con.createStatement();
                        ResultSet rs = st.executeQuery("select max(ID_Bill) from Bill");
                        if(rs.next()){  
                            int id = rs.getInt(1);
                            id = id+1;
                            String str = String.valueOf(id);
                            jTextField1.setText(str);
                        }else{
                            jTextField1.setText("1");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jButton2.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                them = 1;
            }
        }else{
                String ID_Bill = jTextField1.getText();
                String Name = jTextField3.getText();
                String NumberPhone = jTextField2.getText();
                String pId = jTextField4.getText();
                String pName = jTextField5.getText();
                String Price = jTextField6.getText();
                String Species = jTextField7.getText();
                String status = "1";
                String dob = jLabel15.getText();
                int paid = 0;
                int Retun = 0;
                if(Name.equals("") ||NumberPhone.equals("") ||pId.equals("") ||pName.equals("") ||Price.equals("") ||Species.equals("")){
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn đủ thông tin");
                }else
                    try {
                        int thongbao1 = JOptionPane.showConfirmDialog(null, "Bạn muốn tạo hoá đơn này?","Select",JOptionPane.YES_NO_OPTION);
                        if (thongbao1 == 0){
                            Connection con = ConnectionProvider.getConnection();
                            Statement st = con.createStatement();
                            st.executeUpdate("insert into Bill values('"+ID_Bill+"','"+pId+"',N'"+pName+"','"+Species+"','"+Price+"',N'"+Name+"','"+NumberPhone+"','"+dob+"','"+status+"','"+paid+"','"+Retun+"')");
                            st.executeUpdate("update Pet set Status = 0 where pId = '"+pId+"' ");
                            JOptionPane.showMessageDialog(null, "Thêm thành công");
                            setVisible(false);
                            new billing1().setVisible(true);
                            }
                    }catch (Exception e) {
                        JOptionPane.showMessageDialog(null,e);
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        if( bang3 == 1){
            int row = jTable3.getSelectedRow();
            if(row >= 0){
                jTextField1.setText(jTable3.getValueAt(row, 0).toString());
                jTextField1.setForeground(new Color(255,0,0));
                jTextField3.setText(jTable3.getValueAt(row, 5).toString());
                jTextField3.setForeground(new Color(0,0,0));
                jTextField2.setText(jTable3.getValueAt(row, 6).toString());
                jTextField2.setForeground(new Color(255,0,0));
                jTextField4.setText(jTable3.getValueAt(row, 1).toString());
                jTextField4.setForeground(new Color(0,0,0));
                jTextField5.setText(jTable3.getValueAt(row, 2).toString());
                jTextField5.setForeground(new Color(255,0,0));
                jTextField6.setText(jTable3.getValueAt(row, 4).toString());
                jTextField6.setForeground(new Color(0,0,0));
                jTextField7.setText(jTable3.getValueAt(row, 3).toString());
                jTextField7.setForeground(new Color(0,0,0));
            }
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals("")||jTextField6.getText().equals("")||jTextField7.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng chọn đơn hàng muốn xoá");
            }else{
                String ID_Bill = jTextField1.getText();
                String pId = jTextField4.getText();
                String pName = jTextField5.getText();
                String Species = jTextField7.getText();
                String Price = jTextField6.getText();
                String Name = jTextField3.getText();
                String NumberPhone = jTextField2.getText();
                int thongBao = JOptionPane.showConfirmDialog(null, "Bạn muốn xoá hoá đơn này?","Select",JOptionPane.YES_NO_OPTION);
                if(thongBao==0){
                    try {
                        Connection con = ConnectionProvider.getConnection();
                        Statement st = con.createStatement();
                        st.executeUpdate("delete from Bill where ID_Bill ='"+ID_Bill+"'");
                        st.executeUpdate("update Pet set Status = 1 where pId = '"+pId+"' ");
                        setVisible(false);
                        new billing1().setVisible(true);
                    } catch (Exception e) {
                    }
                }
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(traTien == 0){
            String ID_Bill = jTextField1.getText();
            String pId = jTextField4.getText();
            String pName = jTextField5.getText();
            String Species = jTextField7.getText();
            String Price = jTextField6.getText();
            String Name = jTextField3.getText();
            String NumberPhone = jTextField2.getText();
            if(ID_Bill.equals("")|| pId.equals("")|| pName.equals("")|| Species.equals("")|| Price.equals("")|| Name.equals("")|| NumberPhone.equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng chọn hoá đơn");
            }else{
                int thongbao = JOptionPane.showConfirmDialog(null, "Bạn muốn thanh toán hoá đơn này?","Select",JOptionPane.YES_NO_OPTION);
                if(thongbao == 0){
                    jButton1.setEnabled(false);
                    jButton3.setEnabled(false);
                    jButton4.setEnabled(false);
                    jLabel25.setVisible(true);
                    jTextField8.setVisible(true);
                    traTien = 1;
                    JOptionPane.showMessageDialog(null, "Điền số tiền khách trả");
                }
            }
        }
        else if(traTien == 1){
            jButton1.setEnabled(false);
            String ID_Bill = jTextField1.getText();
            String pId = jTextField4.getText();
            String pName = jTextField5.getText();
            String Species = jTextField7.getText();
            String Price = jTextField6.getText();
            String Name = jTextField3.getText();
            String NumberPhone = jTextField2.getText();
            String Paid = jTextField8.getText();
            long tienTra = Long.parseLong(Paid);
            long giaTien = Long.parseLong(Price);
            long tienThua = tienTra-giaTien;
            String Retun = String.valueOf(tienThua);
            if(Paid.equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng điền số tiền khách đưa");
            }else if(tienTra<giaTien){
                JOptionPane.showMessageDialog(null, "Tiền khách trả không đủ");
            }
            else{
                int thongBao = JOptionPane.showConfirmDialog(null, "Thanh toán?","Select",JOptionPane.YES_NO_OPTION);
                if(thongBao==0){
                    try {
                                Connection con = ConnectionProvider.getConnection();
                                Statement st = con.createStatement();
                                st.executeUpdate("update Bill set Status = 0 ,  Paid = '"+Paid+"',Retun='"+Retun+"' where ID_Bill ='"+ID_Bill+"'");
                                setVisible(false);
                                new billing1().setVisible(true);
                            } catch (Exception e) {
                            }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String temp = jComboBox2.getSelectedItem().toString();
        MessageFormat header;
        if(temp.equals("Unconfirmed")){
           header = new MessageFormat("Danh sách hoá đơn chưa thanh toán");
        }else{
           header = new MessageFormat("Danh sách hoá đơn đã được thanh toán");
        }
        MessageFormat footer = new MessageFormat("page {0,number,integer}");
        try {
            jTable3.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String ID_Bill = jTextField1.getText();
        String pName = jTextField5.getText();
        String Price = jTextField6.getText();
        String Name = jTextField3.getText();
        String NumberPhone = jTextField2.getText();
        String Species = jTextField7.getText();
        String path = "E:\\";
        String paid = "";
        String retun = "";
        String date = "";
        try {
            Connection con = ConnectionProvider.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select Name,pName from Bill where ID_Bill = '"+ID_Bill+"'");
            Name = rs.getString("Name");
            pName = rs.getString("pName");
        } catch (Exception e) {
        }
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            try {
                Connection con = ConnectionProvider.getConnection();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select ID_Bill,pId,pName,Species,Price,Date,Paid,Retun from Bill where ID_Bill = '"+ID_Bill+"'");
                if(rs.next()){
                    date = rs.getString("Date");
                    paid = rs.getString("Paid");
                    retun = rs.getString("Retun");
                }
            } catch (Exception e) {
            }
            if(ID_Bill.equals("")||pName.equals("")||Price.equals("")||Name.equals("")||NumberPhone.equals("")||Species.equals("")){
                JOptionPane.showMessageDialog(null, "Chọn hoá đơn");
            }else{
                int thongbao = JOptionPane.showConfirmDialog(null, "In hoá đơn này?","Select",JOptionPane.YES_NO_OPTION);
                if(thongbao==0){
                    PdfWriter.getInstance(doc,new FileOutputStream(path+ID_Bill+"-"+Name+".pdf"));
                    doc.open();
                    Paragraph paragraph1 = new Paragraph("                                                        Pet Management System\n                                                                                                     Contact Number: 19001506\n\n");
                    doc.add(paragraph1);
                    Paragraph paragraph2 = new Paragraph("Date & Time: "+date+ " " + jLabel14.getText()+"\nBuyer Details:\nName :"+Name+"\nPhone Number: "+NumberPhone+"\n\n");
                    doc.add(paragraph2);
                    Paragraph paragraph3 = new Paragraph("Pet Name: "+pName+"\n");
                    doc.add(paragraph3);
                    Paragraph paragraph4 = new Paragraph("Species: "+Species+"\n");
                    doc.add(paragraph4);
                    Paragraph paragraph5 = new Paragraph("Price: "+Price+"\nPaid Amount: "+paid+"\nReturn Amount: "+retun+"\n\nThanks you for Visiting!\nPMS");
                    doc.add(paragraph5);
                    JOptionPane.showMessageDialog(null, "Tạo hoá đơn thành công!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new revenue().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
